<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="پلتفرم یکپارچه و برندپذیر مدیریت باشگاه؛ اعضا، حضور، کلاس، کیف پول، کافه و گزارش در یک محصول."><title>Gym OS — سیستم‌عامل رشد باشگاه</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="marketing-page">
<header class="marketing-nav"><a href="#" class="marketing-logo"><span><x-icon name="dumbbell"/></span><b>GYM OS</b></a><nav><a href="#product">محصول</a><a href="#modules">ماژول‌ها</a><a href="#brands">برند اختصاصی</a></nav><a class="marketing-cta" href="{{ auth()->check()?route('tenant.dashboard'):route('login') }}">{{ auth()->check()?'ورود به پنل':'مشاهده نسخه دمو' }}</a></header>
<main>
<section class="marketing-hero"><div class="hero-aura hero-aura-one"></div><div class="hero-aura hero-aura-two"></div><div class="hero-copy"><span class="hero-pill"><i></i> ساخته‌شده برای باشگاه‌های رو به رشد</span><h1>باشگاهت را اداره نکن؛<br><em>هوشمندانه رشدش بده.</em></h1><p>اعضا، کلاس‌ها، حضور، پرداخت، کیف پول و کافه در یک فضای سریع و زیبا—با برند و هویت کاملاً اختصاصی شما.</p><div class="hero-actions"><a class="marketing-cta marketing-cta-large" href="{{ route('login') }}">شروع تجربه محصول <span>←</span></a><a class="hero-link" href="#modules">دیدن قابلیت‌ها</a></div><div class="hero-trust"><span>بدون نیاز به سخت‌افزار خاص</span><span>آماده چند شعبه</span><span>داده‌های کاملاً مجزا</span></div></div>
<div class="hero-product"><div class="product-window"><div class="product-top"><span></span><span></span><span></span><b>باشگاه آوان</b></div><div class="product-body"><aside><i></i>@for($i=0;$i<6;$i++)<span class="{{ $i===0?'active':'' }}"></span>@endfor</aside><section><div class="mock-head"><div><small>امروز، یک روز پرانرژی</small><strong>داشبورد مدیریت</strong></div><button>پذیرش سریع</button></div><div class="mock-stats"><article><small>اعضای فعال</small><b>۱,۲۸۴</b><i>+۱۲٪</i></article><article><small>حضور امروز</small><b>۱۸۶</b><i>+۸٪</i></article><article><small>فروش کافه</small><b>۲.۸ م</b><i>امروز</i></article></div><div class="mock-chart"><div class="chart-bars">@foreach([42,66,52,78,62,88,73,95,82,100] as $h)<i style="--h:{{$h}}%"></i>@endforeach</div></div></section></div></div><div class="floating-note note-one"><span>✓</span><div><b>پرداخت موفق</b><small>از کیف پول عضو</small></div></div><div class="floating-note note-two"><span>۱۸۶</span><div><b>ورود امروز</b><small>۱۲٪ بیشتر از دیروز</small></div></div></div>
</section>
<section id="product" class="marketing-strip"><span>مدیریت اعضا</span><i></i><span>کلاس و مربی</span><i></i><span>کیف پول</span><i></i><span>کافه</span><i></i><span>گزارش زنده</span></section>
<section id="modules" class="marketing-section"><div class="section-heading"><span>یک هسته، هر قابلیتی که لازم دارید</span><h2>از روز اول ساده.<br>برای فردا بی‌نهایت.</h2><p>فقط ماژول‌هایی که کسب‌وکار شما نیاز دارد فعال می‌شوند؛ داده و تجربه کاربری همچنان یکپارچه می‌ماند.</p></div><div class="feature-bento"><article class="feature-large feature-indigo"><span class="feature-icon"><x-icon name="users"/></span><h3>عضو در مرکز همه‌چیز</h3><p>پرونده، عضویت، پرداخت، حضور، کلاس و اعتبار عضو در یک نمای واحد.</p><div class="member-stack"><i></i><i></i><i></i><b>+۱,۲۸۱</b></div></article><article><span class="feature-icon"><x-icon name="wallet"/></span><h3>کیف پول امن</h3><p>دفترکل تغییرناپذیر و خرید سریع از خدمات باشگاه.</p></article><article><span class="feature-icon"><x-icon name="activity"/></span><h3>پذیرش بی‌اصطکاک</h3><p>ورود QR و کنترل اعتبار عضویت در چند ثانیه.</p></article><article class="feature-wide"><div><span class="feature-icon"><x-icon name="calendar"/></span><h3>کلاس، مربی و ظرفیت</h3><p>برنامه‌ریزی، رزرو و حضور؛ بدون دفتر و پیام‌های پراکنده.</p></div><div class="mini-calendar">@for($i=0;$i<14;$i++)<i class="{{ in_array($i,[2,5,8,12])?'marked':'' }}"></i>@endfor</div></article></div></section>
<section id="brands" class="brand-story"><div><span>White-label واقعی</span><h2>محصول ما،<br>با امضای برند شما.</h2><p>رنگ، لوگو، تراکم و فرم بصری هر باشگاه مستقل است. یک زیرساخت پایدار نگه می‌دارید، اما هر مشتری محصولی متعلق به خودش می‌بیند.</p><a href="{{ route('login') }}" class="hero-link">ورود به استودیوی برند ←</a></div><div class="brand-cards"><article class="brand-card brand-card-one"><small>ATLAS</small><b>قدرت، هر روز.</b></article><article class="brand-card brand-card-two"><small>AVAAN</small><b>حرکت با انرژی.</b></article><article class="brand-card brand-card-three"><small>FORMA</small><b>تعادل در زندگی.</b></article></div></section>
<section class="final-cta"><span>آماده‌اید متفاوت مدیریت کنید؟</span><h2>باشگاه بعدی که رشد می‌کند،<br>می‌تواند باشگاه شما باشد.</h2><a href="{{ route('login') }}" class="marketing-cta marketing-cta-large">ورود به نسخه نمایشی <span>←</span></a></section>
</main><footer><a href="#" class="marketing-logo"><span><x-icon name="dumbbell"/></span><b>GYM OS</b></a><p>زیرساخت یکپارچه رشد باشگاه‌های مدرن</p><small>© {{ date('Y') }} — تمامی حقوق محفوظ است.</small></footer>
</body></html>
