<x-layouts.app title="تغذیه و تمرین">
<section class="page-hero"><div><p class="section-kicker">پرونده عملکرد</p><h1 class="page-title">{{ $member->full_name }}</h1><p class="page-subtitle">برنامه غذایی، خوراک روزانه، رکورد تمرین و حضور در یک نمای منظم.</p></div>@if($isOwner)<div class="flex gap-2"><form method="POST" action="{{ route('tenant.wellness.check-in',$member) }}">@csrf<x-button>ثبت ورود</x-button></form><form method="POST" action="{{ route('tenant.wellness.check-out',$member) }}">@csrf<x-button variant="secondary">ثبت خروج</x-button></form></div>@elseif($roster->isNotEmpty())<div class="flex items-center gap-2"><span class="text-sm muted">شاگرد:</span><select class="field" onchange="if(this.value)window.location.href='{{ route('tenant.wellness.index') }}/'+encodeURIComponent(this.value)"><option value="{{ $member->id }}" selected>{{ $member->full_name }}</option>@foreach($roster as $m)@if($m->id !== $member->id)<option value="{{ $m->id }}">{{ $m->full_name }}</option>@endif@endforeach</select></div>@endif</section>
@if($errors->any())<x-alert tone="danger" class="mb-6">{{ $errors->first() }}</x-alert>@endif
@if(!$isOwner && ($canTraining || $canNutrition))
<section class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
    <x-stat-card label="آخرین وزن" :value="$measurements->last()?->weight_kg ? $measurements->last()->weight_kg.' کیلو' : '—'" icon="activity"/>
    <x-stat-card label="برنامه‌های تمرینی" :value="(string) $programs->count()" icon="dumbbell"/>
    <x-stat-card label="جلسات تمرین" :value="(string) $sessions->count()" icon="activity"/>
    <x-stat-card label="حضورها" :value="(string) $attendances->count()" icon="calendar"/>
</section>
@endif
<div class="wellness-grid">
 <section class="premium-card wellness-panel"><h2>برنامه غذایی</h2>@forelse($plans as $plan)<article class="timeline-card"><strong>{{ $plan->title }}</strong><small>{{ $plan->starts_on->format('Y-m-d') }} · {{ $plan->goal }}</small>@foreach($plan->items as $item)<p><b>{{ $item->meal_name }} {{ $item->suggested_at }}</b><br>{{ $item->foods }}</p>@endforeach@if($canNutrition)<a class="btn-secondary mt-2" href="{{ route('tenant.wellness.plans.edit',$plan) }}">ویرایش</a>@endif</article>@empty<x-empty-state title="هنوز برنامه‌ای ثبت نشده"/>@endforelse</section>
 <section class="premium-card wellness-panel"><h2>رکورد تمرین‌ها</h2>@forelse($sessions as $session)<article class="timeline-card"><strong>{{ $session->title ?: 'جلسه تمرین' }} · {{ $session->performed_on->format('Y-m-d') }}</strong>@foreach($session->sets as $set)<p>{{ $set->exercise_name }} — ست {{ $set->set_number }}، {{ $set->weight_kg ?: '—' }} کیلو، {{ $set->repetitions ?: '—' }} تکرار</p>@endforeach</article>@empty<x-empty-state title="هنوز تمرینی ثبت نشده"/>@endforelse</section>
 <section class="premium-card wellness-panel"><h2>برنامه تمرینی</h2>@forelse($programs as $program)<article class="timeline-card"><div class="flex items-center justify-between"><strong>{{ $program->title }}</strong><x-badge :tone="$program->status==='active'?'success':($program->status==='completed'?'warning':'neutral')">{{ ['draft'=>'پیش‌نویس','active'=>'فعال','completed'=>'تکمیل‌شده','archived'=>'آرشیو'][$program->status]??$program->status }}</x-badge></div><small>{{ $program->starts_on->format('Y-m-d') }} تا {{ $program->ends_on?->format('Y-m-d')??'—' }} · {{ $program->goal }}</small>@foreach($program->days as $day)<p><b>روز {{ $day->day_number }}{{ $day->title ? ' — '.$day->title : '' }}</b>@if($day->sessions->isNotEmpty()) <x-badge tone="success">اجرا شده</x-badge>@endif@foreach($day->sets as $set)<br>{{ $set->exercise_name }} — {{ $set->set_number }} ست، {{ $set->weight_kg ?: '—' }} کیلو، {{ $set->repetitions ?: '—' }} تکرار@endforeach</p>@endforeach@if($program->feedback->isNotEmpty())<div class="mt-2 space-y-1">@foreach($program->feedback as $fb)<p class="text-xs muted"><b>{{ $fb->user->name }}:</b> {{ $fb->body }}</p>@endforeach</div>@endif@if($isOwner || $canTraining)<form class="mt-2 flex gap-2" method="POST" action="{{ route('tenant.wellness.programs.feedback',$program) }}">@csrf<x-input name="body" label="بازخورد"/><x-button type="submit" variant="secondary">ارسال</x-button></form>@endif@if($canTraining || ($isOwner && !$program->coach_id))<div class="mt-2 flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('tenant.wellness.programs.edit',$program) }}">ویرایش</a><form class="flex gap-2" method="POST" action="{{ route('tenant.wellness.programs.status',$program) }}">@csrf @method('PATCH')<select class="field" name="status"><option value="draft" @selected($program->status==='draft')>پیش‌نویس</option><option value="active" @selected($program->status==='active')>فعال</option><option value="completed" @selected($program->status==='completed')>تکمیل‌شده</option><option value="archived" @selected($program->status==='archived')>آرشیو</option></select><x-button type="submit" variant="secondary">تغییر وضعیت</x-button></form></div>@endif</article>@empty<x-empty-state title="برنامه تمرینی ثبت نشده" description="مربی تمرین یا خود عضو می‌تواند برنامه بنویسد."/>@endforelse</section>
 @if($isOwner)<section class="premium-card wellness-panel"><h2>درخواست‌های من</h2>@forelse($requests as $req)<article class="timeline-card"><strong>{{ $req->type==='assign'?'درخواست مربی':'درخواست برنامه' }} · {{ $req->domain==='training'?'تمرین':'تغذیه' }}</strong><x-badge :tone="$req->status==='pending'?'warning':($req->status==='approved'?'success':'neutral')">{{ ['pending'=>'در انتظار','approved'=>'تأییدشده','rejected'=>'ردشده'][$req->status]??$req->status }}</x-badge>@if($req->coach)<p>مربی: {{ $req->coach->full_name }}</p>@endif@if($req->message)<p>{{ $req->message }}</p>@endif@if($req->review_note)<p class="muted">پاسخ: {{ $req->review_note }}</p>@endif</article>@empty<x-empty-state title="درخواستی ثبت نشده"/>@endforelse</section>@endif
 <section class="premium-card wellness-panel"><h2>خوراک روزانه</h2>@forelse($foodLogs as $log)<article class="timeline-card"><strong>{{ $log->meal_name ?: 'وعده غذایی' }}</strong><small>{{ $log->consumed_at->format('Y-m-d H:i') }}</small><p>{{ $log->foods }}</p></article>@empty<x-empty-state title="هنوز خوراکی ثبت نشده"/>@endforelse</section>
 <section class="premium-card wellness-panel"><h2>ورود و خروج</h2>@forelse($attendances as $a)<article class="timeline-card"><strong>{{ $a->checked_in_at->format('Y-m-d H:i') }}</strong><small>خروج: {{ $a->checked_out_at?->format('H:i') ?: 'هنوز داخل باشگاه' }}</small></article>@empty<x-empty-state title="سابقه‌ای وجود ندارد"/>@endforelse</section>
</div>
<div class="wellness-grid">
 <section class="premium-card wellness-panel"><h2>نمودار پیشرفت وزن</h2><x-weight-chart :measurements="$measurements"/></section>
 <section class="premium-card wellness-panel"><h2>اندازه‌گیری‌های دوره‌ای</h2>@forelse($measurements->reverse() as $m)<article class="timeline-card"><strong>{{ $m->measured_on->format('Y-m-d') }} · {{ $m->weight_kg ?: '—' }} کیلو</strong><small>چربی {{ $m->body_fat_percent ?: '—' }}٪ · دور کمر {{ $m->waist_cm ?: '—' }} سانتی‌متر</small></article>@empty<x-empty-state title="اندازه‌گیری ثبت نشده"/>@endforelse</section>
 <section class="premium-card wellness-panel"><h2>تصاویر پیشرفت خصوصی</h2><div class="progress-photo-grid">@forelse($photos as $photo)<figure><img src="{{ route('tenant.wellness.photos.show',$photo) }}" alt="تصویر پیشرفت {{ $photo->view_type }}" loading="lazy"><figcaption>{{ $photo->captured_on->format('Y-m-d') }} · {{ $photo->visibility==='private'?'فقط من':'مربی‌های من' }}</figcaption></figure>@empty<x-empty-state title="تصویری بارگذاری نشده"/>@endforelse</div></section>
 <section class="premium-card wellness-panel"><h2>آسیب‌دیدگی و محدودیت‌ها</h2>@forelse($injuries as $injury)<article class="timeline-card"><strong>{{ $injury->title }} · {{ $injury->body_area }}</strong><small>{{ $injury->occurred_on->format('Y-m-d') }} · {{ ['mild'=>'خفیف','moderate'=>'متوسط','severe'=>'شدید'][$injury->severity]??$injury->severity }}</small><p>{{ $injury->restrictions }}</p></article>@empty<x-empty-state title="محدودیتی ثبت نشده"/>@endforelse</section>
</div>
<div class="wellness-forms">
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.measurements',$member) }}">@csrf<h2>ثبت اندازه‌گیری</h2><x-input type="date" name="measured_on" label="تاریخ" required/><div class="grid grid-cols-2 gap-2"><x-input type="number" step="0.01" name="weight_kg" label="وزن (کیلو)"/><x-input type="number" step="0.01" name="body_fat_percent" label="درصد چربی"/><x-input type="number" step="0.01" name="waist_cm" label="دور کمر"/><x-input type="number" step="0.01" name="chest_cm" label="دور سینه"/></div><x-button>ثبت اندازه‌گیری</x-button></form>
@if($isOwner)
<form class="premium-card wellness-panel" method="POST" enctype="multipart/form-data" action="{{ route('tenant.wellness.photos',$member) }}">@csrf<h2>تصویر پیشرفت</h2><x-input type="file" name="photo" label="JPEG، PNG یا WebP؛ حداکثر ۵ مگابایت" accept="image/jpeg,image/png,image/webp" required/><x-input type="date" name="captured_on" label="تاریخ تصویر" required/><label class="label">زاویه</label><select class="field" name="view_type"><option value="front">روبرو</option><option value="side">نیم‌رخ</option><option value="back">پشت</option></select><label class="label mt-3">حریم خصوصی</label><select class="field" name="visibility"><option value="private">فقط خودم</option><option value="coaches">مربی‌های منتسب من</option></select><label class="mt-4 flex gap-2 text-sm"><input type="checkbox" name="consent" value="1" required> با ذخیره این تصویر حساس و سطح دسترسی انتخاب‌شده موافقم.</label><x-button class="mt-4">بارگذاری خصوصی</x-button></form>
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.injuries',$member) }}">@csrf<h2>ثبت آسیب‌دیدگی</h2><x-input name="title" label="عنوان" required/><x-input name="body_area" label="ناحیه بدن" required/><label class="label">شدت</label><select class="field" name="severity"><option value="mild">خفیف</option><option value="moderate">متوسط</option><option value="severe">شدید</option></select><div class="grid grid-cols-2 gap-2 mt-3"><x-input type="date" name="occurred_on" label="تاریخ وقوع" required/><x-input type="date" name="expected_recovery_on" label="بهبود احتمالی"/></div><x-textarea name="restrictions" label="حرکت‌ها و محدودیت‌های ممنوع" required/><x-textarea name="notes" label="یادداشت"/><label class="flex gap-2 text-sm"><input type="checkbox" name="training_coach_visibility" value="1"> با نمایش به مربی تمرین موافقم</label><x-button class="mt-4">ثبت محدودیت</x-button></form>
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.food',$member) }}">@csrf<h2>ثبت خوراک امروز</h2><x-input type="datetime-local" name="consumed_at" label="زمان" required/><x-input name="meal_name" label="نام وعده"/><x-textarea name="foods" label="چه چیزهایی خوردید؟" required/><x-textarea name="notes" label="یادداشت"/><label class="flex gap-2 text-sm"><input type="checkbox" name="coach_visibility" value="1"> مربی‌های من بتوانند ببینند</label><x-button class="mt-4">ذخیره خوراک</x-button></form>
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.coach-requests.store',$member) }}">@csrf<h2>درخواست مربی یا برنامه</h2><x-select name="type" label="نوع درخواست"><option value="assign">درخواست مربی</option><option value="program">درخواست برنامه</option></x-select><x-select name="domain" label="دامنه"><option value="training">تمرین</option><option value="nutrition">تغذیه</option></x-select><x-select name="coach_id" label="مربی (اختیاری)"><option value="">هر مربی / مربی پیش‌فرض</option>@foreach($coaches as $coach)<option value="{{ $coach->id }}">{{ $coach->full_name }} — {{ $coach->coach_type_label }}</option>@endforeach</x-select><x-textarea name="message" label="پیام"/><x-button class="mt-4">ثبت درخواست</x-button></form>
@endif
@if($isOwner || $canTraining)
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.workouts',$member) }}">@csrf<h2>ثبت رکورد جلسه</h2><x-input type="date" name="performed_on" label="تاریخ" required/><x-input name="title" label="عنوان جلسه"/><x-select name="program_day_id" label="اجرای روز برنامه (اختیاری)"><option value="">بدون برنامه</option>@foreach($programs as $program)@foreach($program->days as $day)<option value="{{ $day->id }}">{{ $program->title }} — روز {{ $day->day_number }}{{ $day->title ? ' ('.$day->title.')' : '' }}</option>@endforeach@endforeach</x-select><x-input name="sets[0][exercise_name]" label="حرکت" required/><div class="grid grid-cols-3 gap-2"><x-input type="number" name="sets[0][set_number]" label="ست" value="1" required/><x-input type="number" step="0.25" name="sets[0][weight_kg]" label="کیلو"/><x-input type="number" name="sets[0][repetitions]" label="تعداد"/></div><x-textarea name="notes" label="یادداشت جلسه"/><x-button>ثبت جلسه</x-button></form>
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.programs',$member) }}">@csrf<h2>برنامه تمرینی جدید</h2><x-input name="title" label="عنوان برنامه" required/><div class="grid grid-cols-2 gap-2"><x-input type="date" name="starts_on" label="شروع" required/><x-input type="date" name="ends_on" label="پایان"/></div><x-input name="goal" label="هدف"/><x-input type="number" name="days[0][day_number]" label="روز" value="1" required/><x-input name="days[0][title]" label="عنوان روز"/><x-input name="days[0][sets][0][exercise_name]" label="حرکت" required/><div class="grid grid-cols-3 gap-2"><x-input type="number" name="days[0][sets][0][set_number]" label="ست" value="1" required/><x-input type="number" step="0.25" name="days[0][sets][0][weight_kg]" label="کیلو"/><x-input type="number" name="days[0][sets][0][repetitions]" label="تعداد"/></div><x-textarea name="notes" label="یادداشت برنامه"/><x-button>ذخیره برنامه</x-button></form>
@endif
@if($canNutrition)
<form class="premium-card wellness-panel" method="POST" action="{{ route('tenant.wellness.plans',$member) }}">@csrf<h2>برنامه غذایی جدید</h2><x-input name="title" label="عنوان" required/><div class="grid grid-cols-2 gap-2"><x-input type="date" name="starts_on" label="شروع" required/><x-input type="date" name="ends_on" label="پایان"/></div><x-input name="goal" label="هدف"/><x-input name="items[0][meal_name]" label="نام وعده" required/><x-input type="time" name="items[0][suggested_at]" label="ساعت پیشنهادی"/><x-textarea name="items[0][foods]" label="مواد غذایی و مقدار" required/><x-textarea name="notes" label="توضیحات مربی"/><x-button>انتشار برنامه</x-button></form>
@endif
</div>
</x-layouts.app>
