<!DOCTYPE html>
<html lang="{{ str_replace('_','-',app()->getLocale()) }}" dir="rtl" class="h-full">
@php($brandGym=app(\App\Core\Tenancy\GymContext::class)->gym())
@php($tenantRole=app(\App\Core\Authorization\TenantRoleService::class)->role(auth()->user()))
@php($portalHome=in_array($tenantRole,['coach','nutrition_coach'],true)?'tenant.wellness.dashboard':($tenantRole==='member'?'tenant.wellness.index':'tenant.dashboard'))
@php($portalCoach=in_array($tenantRole,['coach','nutrition_coach'],true)?app(\App\Modules\Commercial\Application\WellnessAccess::class)->coachFor(auth()->user()):null)
@php($managerLinks=[['dashboard','tenant.dashboard','dashboard','داشبورد'],['members','tenant.members.index','users','اعضا'],['membership_plans','tenant.plans.index','shield','طرح‌های عضویت'],['attendance','tenant.attendance.index','activity','پذیرش سریع'],['classes','tenant.classes.index','calendar','کلاس‌ها'],['coaches','tenant.coaches.index','users','مربیان'],['wellness','tenant.wellness.templates.index','dumbbell','قالب‌های تمرین'],['payments','tenant.payments.index','wallet','پرداخت‌ها'],['wallet','tenant.wallets.index','wallet','کیف پول'],['cafe','tenant.cafe.index','coffee','کافه'],['branches','tenant.branches.index','building','شعب'],['reports','tenant.reports.index','dashboard','گزارش‌ها'],['activity','tenant.activity.index','activity','فعالیت‌ها'],['branding','tenant.branding.edit','sparkles','ظاهر و برند'],['settings','tenant.settings','settings',__('ui.settings')]])
@php($staffLinks=[['dashboard','tenant.dashboard','dashboard','داشبورد'],['members','tenant.members.index','users','اعضا'],['attendance','tenant.attendance.index','activity','پذیرش'],['classes','tenant.classes.index','calendar','کلاس‌ها'],['coaches','tenant.coaches.index','users','مربیان']])
@php($accountantLinks=[['dashboard','tenant.dashboard','dashboard','داشبورد'],['members','tenant.members.index','users','اعضا'],['payments','tenant.payments.index','wallet','پرداخت‌ها'],['wallet','tenant.wallets.index','wallet','کیف پول'],['reports','tenant.reports.index','dashboard','گزارش‌ها']])
@php($coachLinks=[['wellness','tenant.wellness.dashboard','dashboard','داشبورد'],['wellness','tenant.wellness.index','activity','ورزشکاران من'],['wellness','tenant.wellness.coach-requests.index','inbox','درخواست‌ها']])
@if($portalCoach?->handlesDomain('training')) @php($coachLinks[]=['wellness','tenant.wellness.templates.index','dumbbell','کتابخانه تمرین']) @endif
@php($coachLinks[]=['wellness','tenant.wellness.profile','users','پروفایل من'])
@php($portalLinks=in_array($tenantRole,['owner','manager'],true)?$managerLinks:($tenantRole==='staff'?$staffLinks:($tenantRole==='accountant'?$accountantLinks:($tenantRole==='member'?[['wellness','tenant.wellness.index','activity','پرتال ورزشکار']]:$coachLinks))))
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="{{ $brandGym->brand_primary }}"><title>{{ $title??__('ui.panel') }} — {{ $brandGym->name }}</title><style>:root{--brand:{{ $brandGym->brand_primary }};--brand-accent:{{ $brandGym->brand_accent }};--radius-brand:{{ ['compact'=>'10px','soft'=>'18px','round'=>'28px'][$brandGym->ui_radius]??'18px' }};--density:{{ $brandGym->ui_density==='compact'?'.82':'1' }};}</style><script>if(localStorage.theme==='dark'||(!('theme'in localStorage)&&matchMedia('(prefers-color-scheme:dark)').matches))document.documentElement.classList.add('dark')</script>@vite(['resources/css/app.css','resources/js/app.js']) @livewireStyles</head>
<body class="app-canvas min-h-full antialiased" data-tenant-role="{{ $tenantRole }}" data-theme-preset="{{ $brandGym->theme_preset }}" data-search-url="{{ in_array($tenantRole,['owner','manager','staff'],true) && app(\App\Core\Modules\ModuleManager::class)->enabled('search')?route('tenant.search'):'' }}" x-data="{sidebar:false,search:false,notices:false}">
<a href="#main-content" class="sr-only focus:not-sr-only focus:fixed focus:z-[70] focus:m-3 focus:rounded-xl focus:bg-white focus:p-3">{{ __('ui.skip_content') }}</a>
<div x-show="sidebar" x-cloak class="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm lg:hidden" @click="sidebar=false"></div>
<aside class="fixed inset-y-0 right-0 z-50 flex w-72 translate-x-full flex-col border-l border-white/6 bg-[#0c101a] p-4 text-white transition-transform duration-200 lg:translate-x-0" :class="{'translate-x-0':sidebar}">
 <div class="flex h-14 items-center justify-between px-2"><a href="{{ route('tenant.dashboard') }}" class="flex items-center gap-3">@if(data_get(app(\App\Core\Tenancy\GymContext::class)->gym()->settings_json,'logo_path'))<img class="size-9 rounded-xl object-cover" src="{{ route('tenant.settings.logo') }}" alt="">@else<span class="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-700 shadow-lg shadow-indigo-950/30"><x-icon name="dumbbell"/></span>@endif<span><strong class="block text-sm">{{ app(\App\Core\Tenancy\GymContext::class)->gym()->name }}</strong><small class="text-[10px] text-slate-500">GYM OS</small></span></a><button class="rounded-lg p-2 text-slate-400 lg:hidden" @click="sidebar=false"><x-icon name="x"/></button></div>
 <div class="my-5 h-px bg-white/6"></div><p class="px-3 text-[10px] font-black tracking-[.18em] text-slate-600">فضای کاری</p>
 <nav class="mt-3 space-y-1">
 @foreach($portalLinks as [$module,$route,$icon,$label])
 @module($module)<a class="nav-link {{ request()->routeIs($route)||request()->routeIs(str_replace('.index','.*',$route))?'nav-link-active':'' }}" href="{{ route($route) }}"><x-icon :name="$icon"/>{{ $label }}</a>@endmodule
 @endforeach
 </nav>
 <div class="mt-auto rounded-2xl border border-white/7 bg-white/[.035] p-3"><p class="truncate text-sm font-bold">{{ auth()->user()->name }}</p><p class="mt-1 truncate text-[11px] text-slate-500">{{ auth()->user()->email }}</p><form method="POST" action="{{ route('account.logout') }}" class="mt-3">@csrf<button class="flex w-full items-center gap-2 rounded-lg py-2 text-xs font-semibold text-slate-400 hover:text-white"><x-icon name="logout" :size="15"/>{{ __('ui.logout') }}</button></form></div>
</aside>
<div class="lg:pr-72">
 <header class="surface sticky top-0 z-30 flex h-16 items-center gap-2 border-b px-4/90 backdrop-blur-xl sm:px-6">
  <button class="icon-btn lg:hidden" @click="sidebar=true" aria-label="{{ __('ui.open_menu') }}"><x-icon name="menu"/></button>
  @if(in_array($tenantRole,['owner','manager','staff'],true))@module('search')<a href="{{ route('tenant.search') }}" class="hidden min-w-0 max-w-md flex-1 items-center gap-3 rounded-xl border px-3.5 py-2 text-sm sm:flex" style="border-color:var(--line);background:var(--surface-muted);color:var(--ink-muted)"><x-icon name="search"/><span class="truncate">جست‌وجو در باشگاه...</span><span class="kbd mr-auto">⌘ K</span></a>@endmodule@endif
  <div class="mr-auto flex items-center gap-2">
   <form method="POST" action="{{ route('account.gyms.switch') }}">@csrf<label for="gym_id" class="sr-only">{{ __('ui.current_gym') }}</label><select id="gym_id" name="gym_id" class="field !min-h-10 max-w-40 !py-1.5 text-xs" onchange="this.form.submit()">@foreach(app(\App\Core\Tenancy\GymAccess::class)->availableFor(auth()->user()) as $gym)<option value="{{ $gym->id }}" @selected($gym->id===app(\App\Core\Tenancy\GymContext::class)->id())>{{ $gym->name }}</option>@endforeach</select></form>
   @module('notifications')@php($unreadNotifications=\App\Models\Notification::query()->where('user_id',auth()->id())->whereNull('read_at')->latest()->limit(5)->get())@php($unreadCount=\App\Models\Notification::query()->where('user_id',auth()->id())->whereNull('read_at')->count())<div class="relative"><button class="icon-btn relative" @click="notices=!notices" aria-label="اعلان‌ها"><x-icon name="bell"/>@if($unreadCount)<span class="absolute left-1.5 top-1.5 grid size-4 place-items-center rounded-full bg-red-500 text-[9px] text-white">{{ min(9,$unreadCount) }}</span>@endif</button><div x-show="notices" x-cloak @click.outside="notices=false" class="premium-card absolute left-0 mt-2 w-80 p-3 shadow-2xl"><div class="flex items-center justify-between p-2"><strong class="text-sm">اعلان‌ها</strong><a href="{{ route('tenant.notifications.index') }}" class="text-xs font-semibold" style="color:var(--brand)">مشاهده همه</a></div>@forelse($unreadNotifications as $unreadNotification)<a href="{{ route('tenant.notifications.read',$unreadNotification) }}" class="mt-2 flex items-start gap-3 rounded-xl bg-[var(--surface-muted)] p-3"><x-icon name="bell" class="mt-0.5 shrink-0" style="color:var(--brand)"/><div class="min-w-0"><p class="truncate text-xs font-bold">{{ $unreadNotification->title }}</p><p class="mt-0.5 text-[11px] leading-5 muted">{{ \Illuminate\Support\Str::limit($unreadNotification->message, 60) }}</p></div></a>@empty<p class="mt-2 p-3 text-center text-xs muted">اعلان جدیدی ندارید.</p>@endforelse</div></div>@endmodule
   <button class="icon-btn" data-theme-toggle aria-label="{{ __('ui.toggle_theme') }}"><x-icon name="sun"/></button>
  </div>
 </header>
 <main id="main-content" class="mobile-safe mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">@if(session('status'))<x-alert class="mb-6">{{ session('status') }}</x-alert>@endif{{ $slot }}</main>
</div>
<nav class="surface fixed inset-x-3 bottom-3 z-30 flex justify-around rounded-2xl border p-1.5 shadow-xl lg:hidden">@foreach(array_slice($portalLinks,0,4) as [$module,$route,$icon,$label])@module($module)<a class="flex flex-1 flex-col items-center gap-1 rounded-xl py-2 text-[10px]" href="{{ route($route) }}"><x-icon :name="$icon" :size="17"/>{{ $label }}</a>@endmodule @endforeach</nav>
<div x-show="search" x-cloak @keydown.escape.window="search=false" class="fixed inset-0 z-[60] flex justify-center bg-slate-950/60 p-4 pt-[12vh] backdrop-blur-sm"><section @click.outside="search=false" role="dialog" aria-modal="true" aria-label="جست‌وجوی سراسری" class="premium-card h-fit w-full max-w-xl overflow-hidden shadow-2xl"><div class="flex items-center gap-3 border-b p-4" style="border-color:var(--line)"><x-icon name="search" class="muted"/><input autofocus class="w-full bg-transparent text-sm outline-none" placeholder="نام، بخش یا عملیات را جست‌وجو کنید..."><button @click="search=false" class="kbd">ESC</button></div><div class="p-4 text-center text-sm muted">برای جست‌وجو شروع به تایپ کنید</div></section></div>
@livewireScripts</body></html>
