<!DOCTYPE html>
<html lang="{{ str_replace('_','-',app()->getLocale()) }}" dir="rtl" class="h-full"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $title??__('ui.platform_management') }} — {{ config('app.name') }}</title><script>if(localStorage.theme==='dark'||(!('theme'in localStorage)&&matchMedia('(prefers-color-scheme:dark)').matches))document.documentElement.classList.add('dark')</script>@vite(['resources/css/app.css','resources/js/app.js']) @livewireStyles</head>
<body class="app-canvas min-h-full antialiased" x-data="{sidebar:false}">
<a href="#main-content" class="sr-only focus:not-sr-only focus:fixed focus:z-[70] focus:m-3 focus:rounded-xl focus:bg-white focus:p-3">{{ __('ui.skip_content') }}</a><div x-show="sidebar" x-cloak class="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm lg:hidden" @click="sidebar=false"></div>
<aside class="fixed inset-y-0 right-0 z-50 flex w-72 translate-x-full flex-col border-l border-white/6 bg-[#0c101a] p-4 text-white transition-transform lg:translate-x-0" :class="{'translate-x-0':sidebar}">
 <div class="flex h-14 items-center justify-between px-2"><a href="{{ route('platform.dashboard') }}" class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-700"><x-icon name="shield"/></span><span><strong class="block text-sm">{{ __('ui.platform_management') }}</strong><small class="text-[10px] text-slate-500">CONTROL CENTER</small></span></a><button class="p-2 text-slate-400 lg:hidden" @click="sidebar=false"><x-icon name="x"/></button></div>
 <div class="my-5 h-px bg-white/6"></div><p class="px-3 text-[10px] font-black tracking-[.18em] text-slate-600">مدیریت سامانه</p><nav class="mt-3 space-y-1"><a class="nav-link {{ request()->routeIs('platform.dashboard')?'nav-link-active':'' }}" href="{{ route('platform.dashboard') }}"><x-icon name="dashboard"/>{{ __('ui.platform_dashboard') }}</a><a class="nav-link {{ request()->routeIs('platform.gyms.*')?'nav-link-active':'' }}" href="{{ route('platform.gyms.index') }}"><x-icon name="building"/>{{ __('ui.gyms') }}</a></nav>
 <div class="mt-auto rounded-2xl border border-white/7 bg-white/[.035] p-3"><x-badge>Platform Admin</x-badge><p class="mt-3 truncate text-xs text-slate-400">{{ auth()->user()->email }}</p><form method="POST" action="{{ route('account.logout') }}" class="mt-2">@csrf<button class="flex items-center gap-2 py-2 text-xs text-slate-400 hover:text-white"><x-icon name="logout" :size="15"/>{{ __('ui.logout') }}</button></form></div>
</aside>
<div class="lg:pr-72"><header class="surface sticky top-0 z-30 flex h-16 items-center gap-3 border-b px-4/90 backdrop-blur-xl sm:px-6"><button class="icon-btn lg:hidden" @click="sidebar=true"><x-icon name="menu"/></button><div class="min-w-0 flex-1"><span class="section-kicker">Platform</span></div><button class="icon-btn" data-theme-toggle aria-label="{{ __('ui.toggle_theme') }}"><x-icon name="sun"/></button></header>
<main id="main-content" class="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8"><nav class="mb-5 flex items-center gap-2 text-xs muted"><a href="{{ route('platform.dashboard') }}">{{ __('ui.platform_management') }}</a>@isset($breadcrumb)<x-icon name="chevron-left" :size="13"/><span>{{ $breadcrumb }}</span>@endisset</nav>@if(session('status'))<x-alert class="mb-6">{{ session('status') }}</x-alert>@endif{{ $slot }}</main></div>@livewireScripts</body></html>
